[tool.black]
target-version = ['py38']
skip-string-normalization = true
exclude = '''
(
  /(
      \.git
    | \.mypy_cache
    | \.ipython
  )/
)
'''

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
use_parentheses = true
line_length = 88
combine_as_imports = true
combine_star = true
known_third_party = ['pydantic', 'freezegun']
skip = [
    '.git',
    '.mypy_cache',
    '.ipython',
]