RATIOS = {
    "P/E": {"measures": "", "description": ""},
    "P/S": {"measures": "", "description": ""},
}
SECTORS = [
    "Retail Trade",
    "Finance",
    "Energy Minerals",
    "Technology Services",
    "Non-Energy Minerals",
    "Communications",
    "Process Industries",
    "Utilities",
    "Consumer Durables",
    "Transportation",
    "Electronic Technology",
    "Producer Manufacturing",
    "Industrial Services",
    "Health Services",
    "Consumer Non-Durables",
    "Miscellaneous",
    "Commercial Services",
    "Health Technology",
    "Consumer Services",
    "Distribution Services",
]
INDUSTRIES = [
    "Internet Retail",
    "Regional Banks",
    "Integrated Oil",
    "Internet Software/Services",
    "Other Metals/Minerals",
    "Precious Metals",
    "Steel",
    "Oil & Gas Production",
    "Food Retail",
    "Wireless Telecommunications",
    "Aluminum",
    "Chemicals: Agricultural",
    "Coal",
    "Electric Utilities",
    "Homebuilding",
    "Investment Banks/Brokers",
    "Specialty Telecommunications",
    "Marine Shipping",
    "Aerospace & Defense",
    "Airlines",
    "Chemicals: Specialty",
    "Insurance Brokers/Services",
    "Other Transportation",
    "Miscellaneous Manufacturing",
    "Electronics/Appliance Stores",
    "Agricultural Commodities/Milling",
    "Financial Conglomerates",
    "Drugstore Chains",
    "Apparel/Footwear Retail",
    "Construction Materials",
    "Railroads",
    "Oilfield Services/Equipment",
    "Real Estate Development",
    "Finance/Rental/Leasing",
    "Trucks/Construction/Farm Machinery",
    "Data Processing Services",
    "Hospital/Nursing Management",
    "Engineering & Construction",
    "Food: Meat/Fish/Dairy",
    "Beverages: Alcoholic",
    "Oil Refining/Marketing",
    "Motor Vehicles",
    "Metal Fabrication",
    "Gas Distributors",
    "Auto Parts: OEM",
    "Electronic Components",
    "Investment Trusts/Mutual Funds",
    "Food: Specialty/Candy",
    "Miscellaneous Commercial Services",
    "Biotechnology",
    "Trucking",
    "Industrial Machinery",
    "Pharmaceuticals: Other",
    "Building Products",
    "Broadcasting",
    "Restaurants",
    "Home Furnishings",
    "Household/Personal Care",
    "Investment Managers",
    "Wholesale Distributors",
    "Industrial Conglomerates",
]
